#ifndef MM_ZAK_SYMBOLS_H
#define MM_ZAK_SYMBOLS_H

#ifndef PAGE_TITLE
#error "Define PAGE_TITLE before including mm-zak.h"
#define PAGE_TITLE "Dummy Title"
#endif

const char *html_preamble =
	"<!DOCTYPE html>\n"
	"<html lang=\"en\">\n"
	"<head>\n"
	"<meta charset=\"utf-8\">\n"
	"<link href=\"https://fonts.googleapis.com/css2?family=Gentium+Book+Basic\" rel=\"stylesheet\">\n"
	"<title>" PAGE_TITLE "</title>\n"
	"<style>\n"
	"table {\n"
	"    border: 1px solid black;\n"
	"}\n"
	"caption {\n"
	"    font-family: 'Gentium Book Basic';\n"
	"    font-size: 20px;\n"
	"}\n"
	"th {\n"
	"    font-family: 'Gentium Book Basic';\n"
	"    font-size: 18px;\n"
	"    font-weight: normal;\n"
	"}\n"
	"svg {\n"
	"    display: inline;\n"
	"    width: 14px;\n"
	"    height: 14px;\n"
	"}\n"
	".symbols {\n"
	"    display: flex;\n"
	"    justify-content: center;\n"
	"    gap: 4px;\n"
	"    width: 85px;\n"
	"}\n"
	"</style>"
	"</head>";

const char *svg_symbols =
	"<svg style=\"display: none\">\n"
	"<defs>\n"
	"<symbol id=\"A\" viewBox=\"0 0 14 14\">\n"
	"<rect x=\"1\" y=\"1\" width=\"12\" height=\"12\" stroke=\"black\" stroke-width=\"2\" fill=\"white\" />\n"
	"</symbol>\n"
	"<symbol id=\"B\" viewBox=\"0 0 14 14\">\n"
	"<rect width=\"14\" height=\"14\" fill=\"black\" />\n"
	"</symbol>\n"
	"<symbol id=\"C\" viewBox=\"0 0 14 14\">\n"
	"<rect x=\"1\" y=\"1\" width=\"12\" height=\"12\" stroke=\"black\" stroke-width=\"2\" fill=\"white\" />\n"
	"<rect x=\"1\" y=\"7\" width=\"12\" height=\"6\" fill=\"black\" />\n"
	"</symbol>\n"
	"<symbol id=\"D\" viewBox=\"0 0 14 14\">\n"
	"<rect x=\"1\" y=\"1\" width=\"12\" height=\"12\" stroke=\"black\" stroke-width=\"2\" fill=\"white\" />\n"
	"<rect x=\"1\" y=\"1\" width=\"12\" height=\"6\" fill=\"black\" />\n"
	"</symbol>\n"
	"<symbol id=\"E\" viewBox=\"0 0 14 14\">\n"
	"<rect width=\"5\" height=\"14\" fill=\"black\" />\n"
	"<rect x=\"9\" width=\"5\" height=\"14\" fill=\"black\" />\n"
	"</symbol>\n"
	"<symbol id=\"F\" viewBox=\"0 0 14 14\">\n"
	"<rect width=\"14\" height=\"5\" fill=\"black\" />\n"
	"<rect y=\"9\" width=\"14\" height=\"5\" fill=\"black\" />\n"
	"</symbol>\n"
	"<symbol id=\"G\" viewBox=\"0 0 14 14\">\n"
	"<rect x=\"1\" y=\"1\" width=\"12\" height=\"12\" stroke=\"black\" stroke-width=\"2\" fill=\"white\"/>\n"
	"<line x1=\"7\" y1=\"1\" x2=\"7\" y2=\"13\" stroke=\"black\" stroke-width=\"2\" />\n"
	"</symbol>\n"
	"<symbol id=\"H\" viewBox=\"0 0 14 14\">\n"
	"<rect x=\"1\" y=\"1\" width=\"12\" height=\"12\" stroke=\"black\" stroke-width=\"2\" fill=\"white\"/>\n"
	"<line x1=\"1\" y1=\"7\" x2=\"13\" y2=\"7\" stroke=\"black\" stroke-width=\"2\" />\n"
	"</symbol>\n"
	"<symbol id=\"I\" viewBox=\"0 0 14 14\">\n"
	"<line x1=\"7\" y1=\"0\" x2=\"7\" y2=\"14\" stroke=\"black\" stroke-width=\"2\" />\n"
	"<line x1=\"0\" y1=\"7\" x2=\"14\" y2=\"7\" stroke=\"black\" stroke-width=\"2\" />\n"
	"</symbol>\n"
	"<symbol id=\"J\" viewBox=\"0 0 14 14\">\n"
	"<rect x=\"1\" y=\"1\" width=\"12\" height=\"12\" stroke=\"black\" stroke-width=\"2\" fill=\"white\"/>\n"
	"<line x1=\"7\" y1=\"1\" x2=\"7\" y2=\"13\" stroke=\"black\" stroke-width=\"2\" />\n"
	"<line x1=\"1\" y1=\"7\" x2=\"13\" y2=\"7\" stroke=\"black\" stroke-width=\"2\" />\n"
	"</symbol>\n"
	"<symbol id=\"K\" viewBox=\"0 0 14 14\">\n"
	"<rect x=\"1\" y=\"1\" width=\"6\" height=\"6\" stroke=\"black\" stroke-width=\"2\" fill=\"white\"/>\n"
	"<rect x=\"7\" y=\"7\" width=\"6\" height=\"6\" stroke=\"black\" stroke-width=\"2\" fill=\"white\"/>\n"
	"</symbol>\n"
	"<symbol id=\"L\" viewBox=\"0 0 14 14\">\n"
	"<rect x=\"1\" y=\"1\" width=\"12\" height=\"12\" stroke=\"black\" stroke-width=\"2\" fill=\"white\"/>\n"
	"<rect x=\"5\" y=\"5\" width=\"4\" height=\"4\" fill=\"black\"/>\n"
	"</symbol>\n"
	"</defs>\n"
	"</svg>";
	
#endif
